# Generated by Django 5.2.5 on 2025-08-11 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('jwURL', models.URLField()),
                ('imgURL', models.URLField()),
                ('imdbID', models.CharField(max_length=20, unique=True)),
                ('jwRating', models.FloatField(blank=True, null=True)),
                ('tomatoMeter', models.FloatField(blank=True, null=True)),
                ('offers', models.JSONField(blank=True, default=list)),
                ('votes', models.ManyToManyField(blank=True, related_name='voted_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
