# Generated by Django 5.2.5 on 2025-09-19 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_backdrops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(related_name='hall_of_fame_attendances', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_of_fame_entries', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Hall of Fame Entry',
                'verbose_name_plural': 'Hall of Fame Entries',
                'ordering': ['-date_watched'],
            },
        ),
    ]
