# Generated by Django 5.2.5 on 2025-09-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_halloffame'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='HallOfFame',
        ),
    ]
